import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";
import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import type { Overwrite, User, ThreadMetadata, ThreadMember, ForumTag, DefaultReaction, Attachment, Embed, Reaction, ChannelMention, MessageReference, MessageSnapshot, MessageActivity, PartialApplication, MessageInteractionMetadata, MessageInteraction, MessageComponent, StickerItem, Sticker, RoleSubscriptionData, ResolvedData, Poll, MessageCall, SharedClientTheme, Role, Emoji, WelcomeScreen, IncidentsData } from "../models/models";

export const discordGuild = sqliteTable("discordGuild", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  icon: text("icon"),
  iconHash: text("iconHash"),
  splash: text("splash"),
  discoverySplash: text("discoverySplash"),
  owner: integer("owner", { mode: "boolean" }),
  ownerId: text("ownerId").notNull(),
  permissions: text("permissions"),
  region: text("region"),
  afkChannelId: text("afkChannelId"),
  afkTimeout: integer("afkTimeout").notNull(),
  widgetEnabled: integer("widgetEnabled", { mode: "boolean" }),
  widgetChannelId: text("widgetChannelId"),
  verificationLevel: integer("verificationLevel").notNull(),
  defaultMessageNotifications: integer("defaultMessageNotifications").notNull(),
  explicitContentFilter: integer("explicitContentFilter").notNull(),
  roles: text("roles", { mode: "json" }).$type<Role[]>().notNull(),
  emojis: text("emojis", { mode: "json" }).$type<Emoji[]>().notNull(),
  features: text("features", { mode: "json" }).$type<string[]>().notNull(),
  mfaLevel: integer("mfaLevel").notNull(),
  applicationId: text("applicationId"),
  systemChannelId: text("systemChannelId"),
  systemChannelFlags: integer("systemChannelFlags").notNull(),
  rulesChannelId: text("rulesChannelId"),
  maxPresences: integer("maxPresences"),
  maxMembers: integer("maxMembers"),
  vanityUrlCode: text("vanityUrlCode"),
  description: text("description"),
  banner: text("banner"),
  premiumTier: integer("premiumTier").notNull(),
  premiumSubscriptionCount: integer("premiumSubscriptionCount"),
  preferredLocale: text("preferredLocale").notNull(),
  publicUpdatesChannelId: text("publicUpdatesChannelId"),
  maxVideoChannelUsers: integer("maxVideoChannelUsers"),
  maxStageVideoChannelUsers: integer("maxStageVideoChannelUsers"),
  approximateMemberCount: integer("approximateMemberCount"),
  approximatePresenceCount: integer("approximatePresenceCount"),
  welcomeScreen: text("welcomeScreen", { mode: "json" }).$type<WelcomeScreen>(),
  nsfwLevel: integer("nsfwLevel").notNull(),
  stickers: text("stickers", { mode: "json" }).$type<Sticker[]>(),
  premiumProgressBarEnabled: integer("premiumProgressBarEnabled", { mode: "boolean" }).notNull(),
  safetyAlertsChannelId: text("safetyAlertsChannelId"),
  incidentsData: text("incidentsData", { mode: "json" }).$type<IncidentsData>(),
},
  (table) => [
    uniqueIndex("discordGuild_id_unique_idx").on(table.id),
  ]);

export type DiscordGuildSelect = InferSelectModel<typeof discordGuild>;
export type DiscordGuildInsert = InferInsertModel<typeof discordGuild>;

export const discordChannel = sqliteTable("discordChannel", {
  id: text("id").primaryKey(),
  type: integer("type").notNull(),
  guildId: text("guildId"),
  position: integer("position"),
  permissionOverwrites: text("permissionOverwrites", { mode: "json" }).$type<Overwrite[]>(),
  name: text("name"),
  topic: text("topic"),
  nsfw: integer("nsfw", { mode: "boolean" }),
  lastMessageId: text("lastMessageId"),
  bitrate: integer("bitrate"),
  userLimit: integer("userLimit"),
  rateLimitPerUser: integer("rateLimitPerUser"),
  recipients: text("recipients", { mode: "json" }).$type<User[]>(),
  icon: text("icon"),
  ownerId: text("ownerId"),
  applicationId: text("applicationId"),
  managed: integer("managed", { mode: "boolean" }),
  parentId: text("parentId"),
  lastPinTimestamp: text("lastPinTimestamp"),
  rtcRegion: text("rtcRegion"),
  videoQualityMode: integer("videoQualityMode"),
  messageCount: integer("messageCount"),
  memberCount: integer("memberCount"),
  threadMetadata: text("threadMetadata", { mode: "json" }).$type<ThreadMetadata>(),
  member: text("member", { mode: "json" }).$type<ThreadMember>(),
  defaultAutoArchiveDuration: integer("defaultAutoArchiveDuration"),
  permissions: text("permissions"),
  flags: integer("flags"),
  totalMessageSent: integer("totalMessageSent"),
  availableTags: text("availableTags", { mode: "json" }).$type<ForumTag[]>(),
  appliedTags: text("appliedTags", { mode: "json" }).$type<string[]>(),
  defaultReactionEmoji: text("defaultReactionEmoji", { mode: "json" }).$type<DefaultReaction>(),
  defaultThreadRateLimitPerUser: integer("defaultThreadRateLimitPerUser"),
  defaultSortOrder: integer("defaultSortOrder"),
  defaultForumLayout: integer("defaultForumLayout"),
},
  (table) => [
    uniqueIndex("discordChannel_id_unique_idx").on(table.id),
  ]);

export type DiscordChannelSelect = InferSelectModel<typeof discordChannel>;
export type DiscordChannelInsert = InferInsertModel<typeof discordChannel>;

export const discordMessage = sqliteTable("discordMessage", {
  id: text("id").primaryKey(),
  channelId: text("channelId").notNull(),
  author: text("author", { mode: "json" }).$type<User>().notNull(),
  content: text("content").notNull(),
  timestamp: text("timestamp").notNull(),
  editedTimestamp: text("editedTimestamp"),
  tts: integer("tts", { mode: "boolean" }).notNull(),
  mentionEveryone: integer("mentionEveryone", { mode: "boolean" }).notNull(),
  mentions: text("mentions", { mode: "json" }).$type<User[]>().notNull(),
  mentionRoles: text("mentionRoles", { mode: "json" }).$type<string[]>().notNull(),
  mentionChannels: text("mentionChannels", { mode: "json" }).$type<ChannelMention[]>(),
  attachments: text("attachments", { mode: "json" }).$type<Attachment[]>().notNull(),
  embeds: text("embeds", { mode: "json" }).$type<Embed[]>().notNull(),
  reactions: text("reactions", { mode: "json" }).$type<Reaction[]>(),
  nonce: text("nonce"),
  pinned: integer("pinned", { mode: "boolean" }).notNull(),
  webhookId: text("webhookId"),
  type: integer("type").notNull(),
  activity: text("activity", { mode: "json" }).$type<MessageActivity>(),
  application: text("application", { mode: "json" }).$type<PartialApplication>(),
  applicationId: text("applicationId"),
  flags: integer("flags"),
  messageReference: text("messageReference", { mode: "json" }).$type<MessageReference>(),
  messageSnapshots: text("messageSnapshots", { mode: "json" }).$type<MessageSnapshot[]>(),
  referencedMessageId: text("referencedMessageId"),
  interactionMetadata: text("interactionMetadata", { mode: "json" }).$type<MessageInteractionMetadata>(),
  interaction: text("interaction", { mode: "json" }).$type<MessageInteraction>(),
  threadId: text("threadId"),
  components: text("components", { mode: "json" }).$type<MessageComponent[]>(),
  stickerItems: text("stickerItems", { mode: "json" }).$type<StickerItem[]>(),
  stickers: text("stickers", { mode: "json" }).$type<Sticker[]>(),
  position: integer("position"),
  roleSubscriptionData: text("roleSubscriptionData", { mode: "json" }).$type<RoleSubscriptionData>(),
  resolved: text("resolved", { mode: "json" }).$type<ResolvedData>(),
  poll: text("poll", { mode: "json" }).$type<Poll>(),
  call: text("call", { mode: "json" }).$type<MessageCall>(),
  sharedClientTheme: text("sharedClientTheme", { mode: "json" }).$type<SharedClientTheme>(),
},
  (table) => [
    uniqueIndex("discordMessage_id_unique_idx").on(table.id),
    index("discordMessage_channelId_idx").on(table.channelId),
    index("discordMessage_referencedMessageId_idx").on(table.referencedMessageId),
  ]);

export type DiscordMessageSelect = InferSelectModel<typeof discordMessage>;
export type DiscordMessageInsert = InferInsertModel<typeof discordMessage>;
