CREATE TABLE `discordChannel` (
	`id` text PRIMARY KEY,
	`type` integer NOT NULL,
	`guildId` text,
	`position` integer,
	`permissionOverwrites` text,
	`name` text,
	`topic` text,
	`nsfw` integer,
	`lastMessageId` text,
	`bitrate` integer,
	`userLimit` integer,
	`rateLimitPerUser` integer,
	`recipients` text,
	`icon` text,
	`ownerId` text,
	`applicationId` text,
	`managed` integer,
	`parentId` text,
	`lastPinTimestamp` text,
	`rtcRegion` text,
	`videoQualityMode` integer,
	`messageCount` integer,
	`memberCount` integer,
	`threadMetadata` text,
	`member` text,
	`defaultAutoArchiveDuration` integer,
	`permissions` text,
	`flags` integer,
	`totalMessageSent` integer,
	`availableTags` text,
	`appliedTags` text,
	`defaultReactionEmoji` text,
	`defaultThreadRateLimitPerUser` integer,
	`defaultSortOrder` integer,
	`defaultForumLayout` integer
);
--> statement-breakpoint
CREATE TABLE `discordGuild` (
	`id` text PRIMARY KEY,
	`name` text NOT NULL,
	`icon` text,
	`banner` text,
	`owner` integer NOT NULL,
	`permissions` text NOT NULL,
	`features` text NOT NULL,
	`approximateMemberCount` integer,
	`approximatePresenceCount` integer
);
--> statement-breakpoint
CREATE TABLE `discordMessage` (
	`id` text PRIMARY KEY,
	`channelId` text NOT NULL,
	`author` text NOT NULL,
	`content` text NOT NULL,
	`timestamp` text NOT NULL,
	`editedTimestamp` text,
	`tts` integer NOT NULL,
	`mentionEveryone` integer NOT NULL,
	`mentions` text NOT NULL,
	`mentionRoles` text NOT NULL,
	`mentionChannels` text,
	`attachments` text NOT NULL,
	`embeds` text NOT NULL,
	`reactions` text,
	`nonce` text,
	`pinned` integer NOT NULL,
	`webhookId` text,
	`type` integer NOT NULL,
	`activity` text,
	`application` text,
	`applicationId` text,
	`flags` integer,
	`messageReference` text,
	`messageSnapshots` text,
	`referencedMessageId` text,
	`interactionMetadata` text,
	`interaction` text,
	`threadId` text,
	`components` text,
	`stickerItems` text,
	`stickers` text,
	`position` integer,
	`roleSubscriptionData` text,
	`resolved` text,
	`poll` text,
	`call` text,
	`sharedClientTheme` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `discordChannel_id_unique_idx` ON `discordChannel` (`id`);--> statement-breakpoint
CREATE UNIQUE INDEX `discordGuild_id_unique_idx` ON `discordGuild` (`id`);--> statement-breakpoint
CREATE UNIQUE INDEX `discordMessage_id_unique_idx` ON `discordMessage` (`id`);--> statement-breakpoint
CREATE INDEX `discordMessage_channelId_idx` ON `discordMessage` (`channelId`);--> statement-breakpoint
CREATE INDEX `discordMessage_referencedMessageId_idx` ON `discordMessage` (`referencedMessageId`);